behaviors:
  TQC:
    trainer_type: tqc
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      learning_rate_schedule: linear
      tau: 0.005
      steps_per_update: 1.0
      save_replay_buffer: false
      init_entcoef: 0.5
      n_quantiles: 25
      n_to_drop: 2
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
