# CognitionLearn - Advanced ML-Agents Interface
#conda env create -f environment.yml

#conda env update -f environment.yml --prune

name: CognitionLearnEnv
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10.12
  - pip=25.2
  - setuptools=78.1.1
  - wheel=0.45.1
  - numpy=1.23.5
  - pytz=2025.2
  - zlib
  - xz
  - ncurses
  - readline
  - tk
  - openssl
  - sqlite
  - libffi
  - bzip2
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-xorgproto
  - qt
  - tzdata
  - pip:
      # ðŸ§  Instala o Torch usando o repositÃ³rio oficial de wheels
      - torch
      - --find-links https://download.pytorch.org/whl/torch_stable.html

      # ðŸš€ Pacotes locais (vocÃª pode ajustar os caminhos depois)
      - -e ../ml-agents
      - -e ../ml-agents-envs

      # ðŸ“¦ Demais dependÃªncias do seu projeto
      - attrs==25.3.0
      - cattrs==1.5.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - filelock==3.19.1
      - fsspec==2025.7.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - h5py==3.14.0
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - idna==3.10
      - jinja2==3.1.6
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - nvitop==1.5.3
      - onnx==1.15.0
      - pettingzoo==1.15.0
      - pillow==11.3.0
      - protobuf==3.20.3
      - psutil==7.1.0
      - pyyaml==6.0.2
      - requests==2.32.5
      - six==1.17.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - triton==3.4.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - PyQt6==6.8.0

# prefix: /media/Store/conda_envs/CognitionLearnEnv
